spring:
  application:
    name: Game Scoring Service
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: game-service
  kafka:
    groupId: game-scoring-service
    bootstrapAddress: http://localhost:9092
    topic: test-topic

springdoc:
  swagger-ui:
    path: /swagger