spring:
  application:
    name: Game Scoring Service
  datasource:
    url: jdbc:h2:file:./data/scores.db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  kafka:
    groupId: game-scoring-service
    bootstrapAddress: http://localhost:9092
    topic: test-topic
