MERGE INTO PLAYERS KEY(ID) VALUES ('1', 'Rishi');
MERGE INTO PLAYERS KEY(ID) VALUES ('2', 'Rishi 1');
MERGE INTO PLAYERS KEY(ID) VALUES ('3', 'Rishi 2');

MERGE INTO GAMES KEY(ID) VALUES ('1', 'GAME 1');
MERGE INTO GAMES KEY(ID) VALUES ('2', 'GAME 2');
MERGE INTO GAMES KEY(ID) VALUES ('3', 'GAME 3');
